name: Run linter and unit tests

on: [push, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_test:
    name: Run linter and unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci --no-fund

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test
