name: Build for pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --no-package-lock --no-fund

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
